export const CONTENT = {
  home: {
    ticker: [
      'Software Engineer',
      'Product Manager',
      'Data Scientist',
      'UX Designer',
      'DevOps Engineer',
      'Marketing Manager',
      'Finance Analyst',
      'Team Lead',
      'Backend Developer',
      'Cloud Architect',
      'Scrum Master',
      'Machine Learning Engineer',
      'Frontend Developer',
      'Operations Manager',
      'Business Analyst',
      'Head of Growth',
    ],
    hero: {
      heading: 'English-Speaking',
      headingAccent: 'Jobs in Germany',
      subtitle:
        'We scrape, filter, and review roles from 20+ major German companies — surfacing only the ones where German is genuinely not required.',
      primaryCta: 'Get Weekly Alerts',
      secondaryCta: 'Browse Jobs',
      stats: [
        ['20+', 'Companies'],
        ['Daily', 'Fresh scrapes'],
      ] as const,
    },
    why: [
      {
        title: 'AI-Filtered',
        body: 'Every listing is scanned to confirm German is not required — not guessed, confirmed.',
      },
      {
        title: 'Daily Scrapes',
        body: 'We scrape 20+ top German employers daily so you always see fresh roles first.',
      },
      {
        title: 'Human Reviewed',
        body: 'A review layer catches AI mistakes. Only quality, relevant roles reach you.',
      },
    ],
    companies: {
      label: 'Hiring partners',
      heading: 'Companies hiring',
      headingAccent: 'English speakers',
      fullDirectoryCta: 'Full directory',
      carouselAriaLeft: 'Scroll left',
      carouselAriaRight: 'Scroll right',
    },
    newsletter: {
      heading: 'Never miss a job drop.',
      subtitle: 'Join 2,000+ professionals. Weekly digest of verified English-only jobs. No spam.',
      emailPlaceholder: 'your@email.com',
      subscribeCta: 'Subscribe',
      success: "You're in — check your inbox soon.",
      error: 'Something went wrong. Please try again.',
    },
    latest: {
      label: 'Fresh picks',
      heading: 'Latest opportunities',
      viewAllCta: 'View all',
      loadMoreCta: 'Load more',
    },
  },
  signup: {
    fallbackError: 'Something went wrong.',
    success: {
      heading: "You're in.",
      subtitle: 'Expect curated English-speaking job alerts in Germany in your inbox every week.',
      cta: 'Browse Jobs Now',
    },
    leftPanel: {
      heading: 'Get job alerts',
      subtitle: 'Join 2,000+ professionals receiving weekly curated English-only job listings in Germany.',
      perks: [
        'Weekly curated job digest to your inbox',
        'No spam — we respect your privacy',
        'English-only roles verified by AI + humans',
      ],
    },
    form: {
      heading: 'Get job alerts',
      subtitle: 'Weekly digest of verified English-only roles in Germany',
      labels: {
        fullName: 'Full Name',
        email: 'Email Address',
        jobInterest: 'Job Interest',
        currentCountry: 'Current Country',
      },
      placeholders: {
        fullName: 'Alex Smith',
        email: 'alex@example.com',
      },
      domainOptions: [
        ['Tech', 'Tech / IT'],
        ['Non-Tech', 'Business / Other'],
      ] as const,
      countryPlaceholder: 'Select your country',
      submitCta: 'Join the list',
      adminPrompt: 'Admin?',
      adminLoginCta: 'Login here',
    },
    countries: [
      'Germany', 'India', 'United Kingdom', 'United States', 'Canada', 'Australia', '--------------------------------', 'Afghanistan', 'Albania', 'Algeria', 'Argentina', 'Armenia', 'Austria', 'Azerbaijan', 'Bahrain', 'Bangladesh', 'Belarus', 'Belgium', 'Bolivia', 'Brazil', 'Bulgaria', 'Cambodia', 'Chile', 'China', 'Colombia', 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic', 'Denmark', 'Ecuador', 'Egypt', 'Estonia', 'Ethiopia', 'Finland', 'France', 'Ghana', 'Greece', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kuwait', 'Latvia', 'Lebanon', 'Lithuania', 'Luxembourg', 'Malaysia', 'Malta', 'Mexico', 'Moldova', 'Montenegro', 'Morocco', 'Nepal', 'Netherlands', 'New Zealand', 'Nigeria', 'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Panama', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania', 'Russia', 'Rwanda', 'Saudi Arabia', 'Serbia', 'Singapore', 'Slovakia', 'Slovenia', 'South Africa', 'Spain', 'Sri Lanka', 'Sweden', 'Switzerland', 'Taiwan', 'Thailand', 'Tunisia', 'Turkey', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan', 'Venezuela', 'Vietnam', 'Zambia', 'Zimbabwe'
    ],
  },
  admin: {
    label: 'Admin',
    reviewQueue: {
      title: 'Review Queue',
      subtitle: (count: number) => `${count} jobs pending AI verification`,
      refreshCta: 'Refresh',
      empty: {
        title: 'All Caught Up!',
        body: 'No jobs pending review. Come back after the next scrape run.',
      },
    },
    rejectedJobs: {
      title: 'Rejected Jobs',
      subtitle: (count: number) => `${count} jobs in trash`,
      refreshCta: 'Refresh',
      empty: {
        title: 'Trash is empty',
        body: 'All good — no rejected jobs here.',
      },
    },
    jobTestLogs: {
      title: 'AI Test Logs',
      subtitle: 'Admin Diagnostics',
      refreshCta: 'Refresh',
      summary: (count: number) => `${count} jobs analyzed (accepted + rejected with AI evidence)`,
      searchPlaceholder: 'Search by title, company, JobID...',
      decisions: ['all', 'accepted', 'rejected'] as const,
      states: {
        noToken: 'No authentication token found. Please log in.',
        expired: 'Your session has expired. Please log in again.',
        failedLoad: 'Failed to load test logs. Please try again.',
        unableTitle: 'Unable to load logs',
        unableBody: 'Please check your authentication and try again.',
        loginCta: 'Login',
        goToLoginCta: 'Go to Login',
        noLogsTitle: 'No logs found',
        noLogsBody: 'No test logs in database yet. Run the scraper first.',
        adjustFiltersBody: 'Try adjusting your filters.',
      },
      labels: {
        jobId: 'JobID:',
        postedPrefix: 'Posted:',
        postedFallback: 'N/A',
        germanRequired: 'German Required',
        yes: 'Yes',
        no: 'No',
        aiEvidence: 'AI Evidence & Reasoning',
        germanEvidence: '🇩🇪 German',
        noEvidence: 'No evidence provided',
        accepted: '✓ Accepted',
        rejected: '✗ Rejected',
        showLess: 'Show less',
        viewFullDescription: 'View full description',
      },
    },
    dashboard: {
      documentTitle: 'Browse English-Speaking Jobs in Germany',
      headerLabel: 'Opportunities',
      defaultTitle: 'All English Jobs',
      subtitle: (count: number) => `${count} verified English-speaking roles`,
      sideHeading: 'Companies',
      allJobs: 'All Jobs',
      empty: {
        title: 'No jobs found',
        body: 'Try a different company or view all roles.',
        clearFilterCta: 'Clear filter',
      },
    },
  },
} as const;
